name: Run .sh File on Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run .sh Script
        run: |
          chmod +x ../../script.sh
          ../../script.sh
